### ISSUE TITLE
Multiple answers

### ISSUE THREAD

**Issue by meghprkh** [felicity-iiith/contest-portal-backend#10]
Contests like cache in require you to have multiple possible answers.

For this we will store a JSON in the answer field of question, so store `['a', 'b', 'c']`.

Then on checkSolution we will do JSON.parse and see if the answer is in the array returned by JSON.parse

**Comment by troublemagnet** [comment]
I'm on this one.

**Comment by Kunalgarg2100** [comment]
I am working on this issue

**Comment by meghprkh** [comment]
via 5b7e982
